import L from "leaflet";
// Codex region map (klightspeed's EliteDangerousRegionMap, via EDMC-ExploData), generated by tools/import_bio_data.py.
import { map as regionRows, names as regionNames } from "../../../src-tauri/data/bio/regions.json";

const X0 = -49985;
const Z0 = -24105;
const CELL_LY = 4096 / 83;
const SIZE = 2048;

/** Galaxy map convention: x to the right, z (towards Sagittarius A*) up. */
export function toLatLng(pos: readonly number[]): L.LatLng {
  return L.latLng(pos[2], pos[0]);
}

function decode(): Uint8Array {
  const grid = new Uint8Array(SIZE * SIZE);
  (regionRows as [number, number][][]).forEach((row, z) => {
    let x = 0;
    for (const [run, id] of row) {
      grid.fill(id, z * SIZE + x, Math.min(SIZE, x + run) + z * SIZE);
      x += run;
    }
  });
  return grid;
}

function regionColor(id: number): [number, number, number] {
  // Golden-angle hues keep neighbouring ids distinct.
  const hue = (id * 137.508) % 360;
  const s = 0.45;
  const l = 0.55;
  const k = (n: number) => (n + hue / 30) % 12;
  const a = s * Math.min(l, 1 - l);
  const f = (n: number) => l - a * Math.max(-1, Math.min(k(n) - 3, 9 - k(n), 1));
  return [f(0) * 255, f(8) * 255, f(4) * 255];
}

/** Region tint, or just the borders between regions (which include the galaxy's outline). */
function renderImage(grid: Uint8Array, part: "fill" | "borders"): string {
  const canvas = document.createElement("canvas");
  canvas.width = SIZE;
  canvas.height = SIZE;
  const ctx = canvas.getContext("2d")!;
  const image = ctx.createImageData(SIZE, SIZE);
  const at = (x: number, z: number) => (x < 0 || z < 0 || x >= SIZE || z >= SIZE ? 0 : grid[z * SIZE + x]);
  for (let z = 0; z < SIZE; z++) {
    for (let x = 0; x < SIZE; x++) {
      const id = grid[z * SIZE + x];
      if (id === 0) continue;
      const border = at(x + 1, z) !== id || at(x - 1, z) !== id || at(x, z + 1) !== id || at(x, z - 1) !== id;
      if (part === "borders" && !border) continue;
      const [r, g, b] = regionColor(id);
      // Canvas rows run top-down; map z runs bottom-up.
      const i = ((SIZE - 1 - z) * SIZE + x) * 4;
      image.data[i] = r;
      image.data[i + 1] = g;
      image.data[i + 2] = b;
      image.data[i + 3] = part === "borders" ? 90 : 22;
    }
  }
  ctx.putImageData(image, 0, 0);
  return canvas.toDataURL();
}

function labels(grid: Uint8Array): { name: string; pos: [number, number, number] }[] {
  const sums = new Map<number, { x: number; z: number; n: number }>();
  for (let z = 0; z < SIZE; z++) {
    for (let x = 0; x < SIZE; x++) {
      const id = grid[z * SIZE + x];
      if (id === 0) continue;
      const s = sums.get(id) ?? { x: 0, z: 0, n: 0 };
      s.x += x;
      s.z += z;
      s.n += 1;
      sums.set(id, s);
    }
  }
  return [...sums].map(([id, s]) => ({
    name: (regionNames as (string | null)[])[id] ?? "",
    pos: [X0 + (s.x / s.n + 0.5) * CELL_LY, 0, Z0 + (s.z / s.n + 0.5) * CELL_LY],
  }));
}

let cached: { grid: Uint8Array; fill: string; borders: string; labels: ReturnType<typeof labels> } | null = null;

function data() {
  if (!cached) {
    const grid = decode();
    cached = { grid, fill: renderImage(grid, "fill"), borders: renderImage(grid, "borders"), labels: labels(grid) };
  }
  return cached;
}

/** Name of the codex region at a position, or null outside the map. */
export function regionAt(pos: readonly number[]): string | null {
  const x = Math.floor((pos[0] - X0) / CELL_LY);
  const z = Math.floor((pos[2] - Z0) / CELL_LY);
  if (x < 0 || z < 0 || x >= SIZE || z >= SIZE) return null;
  return (regionNames as (string | null)[])[data().grid[z * SIZE + x]] ?? null;
}

/**
 * Region layers, built once. Borders are only worth showing zoomed out: up close the ~50 ly grid they follow
 * turns them into staircases.
 */
export function regionLayers(): { fill: L.ImageOverlay; borders: L.ImageOverlay; labels: L.LayerGroup } {
  const cached = data();
  const bounds = L.latLngBounds(L.latLng(Z0, X0), L.latLng(Z0 + SIZE * CELL_LY, X0 + SIZE * CELL_LY));
  const fill = L.imageOverlay(cached.fill, bounds, { interactive: false, className: "region-image" });
  const borders = L.imageOverlay(cached.borders, bounds, { interactive: false, className: "region-image" });
  const group = L.layerGroup(
    cached.labels.map((l) =>
      L.marker(toLatLng(l.pos), {
        interactive: false,
        keyboard: false,
        icon: L.divIcon({ className: "region-label", html: l.name, iconSize: undefined }),
      }),
    ),
  );
  return { fill, borders, labels: group };
}
